### ISSUE TITLE
Fate grand order

### ISSUE THREAD

**Issue by tempetahu0** [wDCat/ANRC#40]
Device : xiaomi mi5
Problem: still got error code 60 with newest version or older

**Comment by dj1818** [comment]
Try to use 0.53 ver. It's good for use on MM roms

**Comment by oakami** [comment]
FGO used to work with ANRC but after the newest update it crashes with error code 92.

**Comment by dj1818** [comment]
1 week ago it worked, anyway

**Comment by dj1818** [comment]
Now i just don't play cuz hello 7.1.1 N

**Comment by wDCat** [comment]
@oakami  go to advanced setting and replace /system/bin/pm to modified version.

**Comment by oakami** [comment]
Ah it resets after every update. That makes sense. Thank you.

**Comment by tempetahu0** [comment]
not working anymore?there's no anrc pop up anymore everytime i open FGO

**Comment by oakami** [comment]
I updated to the latest ANRC and now FGO crashes with error code 60. Android 6.0.1. Here are some screenshots. http://imgur.com/a/NQOxF

**Comment by wDCat** [comment]
@oakami fixed at v0.0.76 _(:зゝ∠)_

**Comment by SquallATF** [comment]
@wDCat ANRC v0.0.76 FC on FGO start
```
01-04 20:49:11.901 30180-30180/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: cat.dcat.roothide, PID: 30180
                                                   java.lang.RuntimeException: Unable to start receiver cat.dcat.roothide.receiver.AppLaunchMsgReceiver: java.lang.IllegalArgumentException: n <= 0: 0
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2680)
                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:156)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:211)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
                                                    Caused by: java.lang.IllegalArgumentException: n <= 0: 0
                                                       at java.util.Random.nextInt(Random.java:182)
                                                       at cat.dcat.roothide.receiver.AppLaunchMsgReceiver.a(AppLaunchMsgReceiver.java:185)
                                                       at cat.dcat.roothide.receiver.AppLaunchMsgReceiver.onReceive(AppLaunchMsgReceiver.java:48)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2673)
                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:156) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:211) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5389) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
```

**Comment by wDCat** [comment]
@SquallATF fixed at v0.0.77

**Comment by Nebelwerfer-G** [comment]
Device: Nexus 5 Hammerhead
System: MoKee MK60.1-hammerhead-170129
ANRC: 0.0.90 20170225
err code 60 on newest version of fgo.
